### ISSUE TITLE
No blur in Windows demo build

### ISSUE THREAD

**Issue by VulumeCode** [sphynx-owner/JFA_driven_motion_blur_demo#4]
I don't see a blur in the demo build for Windows, not with my GPU enabled or without. I do see a blur in the Drift Hover demo.

**Comment by sphynx-owner** [comment]
Hey, thank you for letting me know. I just downloaded the demo and it works for me right away. Do you refer to the addon by any chance? cause that was just broken and I think I fixed that. If not, try and see if you can find a way to get it to work so I can have a clearer reason as to why it does not work for you.

**Comment by VulumeCode** [comment]
I downloaded this one 

> Windows: [Bistro-Demo-Tweaked-Windows.zip](https://github.com/Jamsers/Bistro-Demo-Tweaked/releases/download/v1.1/Bistro-Demo-Tweaked-Windows.zip)

I tried again on my work laptop now, no change. Both computers have NVidia cards, but not much else in common. Also the .exe in that zip have "date created" 27/12/2023. Is it just the regular demo?

**Comment by sphynx-owner** [comment]
i see now. You are looking at the section of the README that came with the environment to which i added the blur. This Zip does not contain my implementation but the base environment. If you want to have my implementation you have to go to code at the top right and download zip file.

**Comment by VulumeCode** [comment]
Makes sense. I suggest removing that part of the readme then, since it's irrelevant to your project.
